### ISSUE TITLE
Problems on Windows 10

### ISSUE THREAD

**Issue by rdspencer** [wwwtyro/canvas-video-generator#5]
I have tried to run the random boxes example on Windows 10, but get the following messages:
Canvas video generator server listening on port 3172.
Begining rendering of your video. This might take a long time...
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Any help would be must appreciated - looks like a great app

**Comment by rdspencer** [comment]
I found the problem - I had not installed ffmpeg.  This applied to Ubuntu as well as Windows.
